### ISSUE TITLE
Admin/addcop

### ISSUE THREAD

**Issue by JessicaxD** [OfficialDarkzy/DRP-Framework#1] opened 2019-05-12 00:58 UTC
Error running system event handling function for resource drp_core: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @drp_core/server.lua:134: attempt to call a nil value (local 'callback')
stack traceback:
        @drp_core/server.lua:134: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:374>
Connection: 7
Connection: 8
1
addcoaddcop 1
1
Error running call reference function for resource drp_police: citizen:/scripting/lua/scheduler.lua:405: @drp_police/commands.lua:7: attempt to index a boolean value (local 'myJob')
stack traceback:
        @drp_police/commands.lua:7: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/cfx> scheduler.lua:389>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:405: in function <citizen:/scripting/lua/scheduler.lua:374>
www
cfx> addcop 3
3
Error running call reference function for resource drp_police: citizen:/scripting/lua/scheduler.lua:405: @drp_police/commands.lua:7: attempt to index a boolean value (local 'myJob')
stack traccfx> eback:
        @drp_police/commands.lua:7: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/scheduler.lua:389>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:405: in function <citizen:/scripting/lua/scheduler.lua:374>
     addcop 3
3
Error running call reference function for resource drp_police: citizen:/scrcfx> ipting/lua/scheduler.lua:405: @drp_police/commands.lua:7: attempt to index a boolean value (local 'myJob')
stack traceback:
        @drp_police/commands.lua:7: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/scheduler.lua:389>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:405: in function <citizen:/scripting/lua/scheduler.lua:374>
1

**Comment by JessicaxD** [comment] 2019-05-12 00:59
When i do /admin and /addcop

**Comment by OfficialDarkzy** [comment] 2019-05-12 09:38
Will sort this today

**Comment by JessicaxD** [comment] 2019-05-12 18:41
Thanks :)

**Comment by OfficialDarkzy** [comment] 2019-05-12 20:43
This is not something i can reproduce, you have either changed the name of the resources or not connected the database correctly

**Comment by JessicaxD** [comment] 2019-05-12 21:43
Config.lua

SQLConfig = {}

-- Connection Configurations
SQLConfig.host = "localhost"
SQLConfig.port = 2000
SQLConfig.apipath = "/external/api"
SQLConfig.secret = "Test"
SQLConfig.community = "CHANGEME"

-- Further Configurations
SQLConfig.CreateTokenOnStart = true

--[[ DO NOT EDIT BELOW ]]--


Config.js


ExternalConfig = {};

// Port API Runs On
ExternalConfig.Server = {
    port: 2000
}

// Database Connection Configs
ExternalConfig.Database = {
    connectionLimit: 100,
    host: "localhost",
    user: "root",
    password: "",
    database: "drp"
};

// API Configs
ExternalConfig.API = {
    route: "/external/api",
    secret: "Test"
}

ExternalConfig.DevModeActive = false;

module.exports.config = ExternalConfig;
module.exports.server = ExternalConfig.Server;
module.exports.database = ExternalConfig.Database;
module.exports.api = ExternalConfig.API;
module.exports.dev = ExternalConfig.DevModeActive;

**Comment by OfficialDarkzy** [comment] 2019-05-12 21:44
Have you changed the resource names?

**Comment by JessicaxD** [comment] 2019-05-12 21:47
No :)

**Comment by JessicaxD** [comment] 2019-05-12 21:48
https://gyazo.com/1d89f1ae04f4b3840a93e9c5d8f18d7f 

Like this right?

**Comment by JessicaxD** [comment] 2019-05-12 22:38
Is it somthing i do wrong?

**Comment by JessicaxD** [comment] 2019-05-14 00:28
Error running call reference function for resource drp_police: citizen:/scripting/lua/scheduler.lua:405: @drp_police/commands.lua:7: attempt to index a boolean value (local 'myJob')
stack traceback:
        @drp_police/commands.lua:7: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/scheduler.lua:389>
stack traceback:
        [C]: in function 'error'
        citizecfx> n:/scripting/lua/scheduler.lua:405: in function <citizen:/scripting/lua/scheduler.lua:374>

**Comment by JessicaxD** [comment] 2019-05-14 00:29
Still getting this one when i try to add myself as a cop

**Comment by OfficialDarkzy** [comment] 2019-05-14 09:41
Because you have to add yourself as a cop in the database then you’ll be able to use the command

**Comment by JessicaxD** [comment] 2019-05-14 12:17
I have tried that aswell

Id = 9, Rank = 6, Division = police, char Id = 27. And still cant use it or do anything

**Comment by OfficialDarkzy** [comment] 2019-05-14 12:33
Are you doing the command in game and not in the console? And this is confusing me because i've just done the command and it works fine :D

**Comment by JessicaxD** [comment] 2019-05-14 12:39
I tried both :)

**Comment by OfficialDarkzy** [comment] 2019-05-14 14:09
hmmmm, do /job in game and tell me what job you are or give an error if it does error.

**Comment by JessicaxD** [comment] 2019-05-14 15:11
It says im unemployment :)

**Comment by OfficialDarkzy** [comment] 2019-05-14 15:18
Are you actually downloading the newest files I have been pushing and fixing to the REPO?

**Comment by JessicaxD** [comment] 2019-05-14 15:19
Yes :)

**Comment by OfficialDarkzy** [comment] 2019-05-14 15:21
This is hurting my brain, because I am doing the command at the moment and it works fine lol. I will be home soon ill rewrite it so its cleaner.

**Comment by JessicaxD** [comment] 2019-05-14 15:23
Like this is correct right? 

https://gyazo.com/7138599887540664617c6dabebb92cf9

**Comment by OfficialDarkzy** [comment] 2019-05-14 15:26
yeah as long as that is your player id, it shouldn't error it should say you are not registered or allowed to do that command. I will be home in 1 hour so i will have another look.

**Comment by JessicaxD** [comment] 2019-05-14 15:37
When i do /addcop id or addcop id in the console, it gives me that error, and when i do it ingame it gives me the error and it says ingame that im not an employee the police force

**Comment by OfficialDarkzy** [comment] 2019-05-14 15:50
yeah its not meant to work in the console.

and yes its meant to say that, you must not have the correct id in the database police table. in "char_id" in the database table did you drop it down and press on your character id?

**Comment by JessicaxD** [comment] 2019-05-14 15:50
Yepp :)

**Comment by OfficialDarkzy** [comment] 2019-05-14 15:56
set your rank to 7.

**Comment by JessicaxD** [comment] 2019-05-14 16:04
Still the same im not an employee the police force

**Comment by OfficialDarkzy** [comment] 2019-05-16 08:09
This is now resolved, I will close the issue ticket.

**Closed by OfficialDarkzy** 2019-05-16 08:09 UTC
